export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAILED = 'FETCH_STORIES_FAILED';
export const REFRESH_STORIES = 'REFRESH_STORIES';
export const REFRESH_STORIES_SUCCESS = 'REFRESH_STORIES_SUCCESS';
export const REFRESH_STORIES_FAILED = 'REFRESH_STORIES_FAILED';

export const FETCH_ITEM = 'FETCH_ITEM';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILED = 'FETCH_ITEM_FAILED';
export const REFRESH_ITEM = 'REFRESH_ITEM';
export const REFRESH_ITEM_SUCCESS = 'REFRESH_ITEM_SUCCESS';
export const REFRESH_ITEM_FAILED = 'REFRESH_ITEM_FAILED';
