export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAILED = 'FETCH_STORIES_FAILED';
export const REFRESH_STORIES = 'REFRESH_STORIES';
export const REFRESH_STORIES_SUCCESS = 'REFRESH_STORIES_SUCCESS';
export const REFRESH_STORIES_FAILED = 'REFRESH_STORIES_FAILED';
